// Code generated by "stringer -type ObjKind,TypKind -output kind_string.go"; DO NOT EDIT.

package aster

import "strconv"

const _ObjKind_name = "BadPkgConTypVarFunLblBuiNil"

var _ObjKind_index = [...]uint8{0, 3, 6, 9, 12, 15, 18, 21, 24, 27}

func (i ObjKind) String() string {
	if i < 0 || i >= ObjKind(len(_ObjKind_index)-1) {
		return "ObjKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ObjKind_name[_ObjKind_index[i]:_ObjKind_index[i+1]]
}

const _TypKind_name = "InvalidBasicArraySliceStructPointerTupleSignatureInterfaceMapChanNamed"

var _TypKind_index = [...]uint8{0, 7, 12, 17, 22, 28, 35, 40, 49, 58, 61, 65, 70}

func (i TypKind) String() string {
	if i < 0 || i >= TypKind(len(_TypKind_index)-1) {
		return "TypKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypKind_name[_TypKind_index[i]:_TypKind_index[i+1]]
}
