// Code generated by "stringer -type Kind"; DO NOT EDIT.

package aster

import "strconv"

const _Kind_name = "InvalidSuspenseBoolIntInt8Int16Int32Int64UintUint8Uint16Uint32Uint64UintptrFloat32Float64Complex64Complex128StringInterfaceChanArraySliceMapFuncStructPtr"

var _Kind_index = [...]uint8{0, 7, 15, 19, 22, 26, 31, 36, 41, 45, 50, 56, 62, 68, 75, 82, 89, 98, 108, 114, 123, 127, 132, 137, 140, 144, 150, 153}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
