language: go
os:
  - linux
  - osx
go:
  - "1.12"
  - "1.13"
go_import_path: github.com/andeya/aster
env:
  - GIMME_ARCH=amd64 GO111MODULE=on
  - GIMME_ARCH=386 GO111MODULE=on
script:
  - go get -d -t ./...
  - go test -v ./...
  - go test -v ./_examples
after_success:
  - bash <(curl -s https://codecov.io/bash)