language: go
os:
  - linux
  - osx
  - windows
go:
  # - "1.10"
  - "1.11"
go_import_path: github.com/henrylee2cn/aster
env:
  - GIMME_ARCH=amd64
  - GIMME_ARCH=386
  - GO111MODULE=on
script:
  - go get -d -t ./...
  - go test -v ./_examples
  - go test -v ./_test
  - go test -v ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)